[package]
name = "file_checker"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.29", features = ["derive"] }
generic-array = "1.2.0"
md-5 = "0.10.6"
sha2 = "0.10.8"
walkdir = "2.5.0"
